package com.jfinal.bean;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePeople<M extends BasePeople<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}

	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setOpera(java.lang.String opera) {
		set("opera", opera);
		return (M)this;
	}

	public java.lang.String getOpera() {
		return getStr("opera");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}    
}
