package com.jfinal.model;

import com.jfinal.bean.BasePeople;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class People extends BasePeople<People> {
	public static final People dao = new People().dao();
	
	public Page<People> list(int pageNumber, int pageSize, String searchName){
		StringBuilder sql = new StringBuilder();
		sql.append("from people where opera<>-1");
		if(StrKit.notBlank(searchName)){
			sql.append(" and name like '%").append(searchName).append("%'");
		}
		Page<People> p = dao.paginate(pageNumber, pageSize, "select *", sql.toString());
		return p;
	}
	
	public boolean opera(int id, String type){
		boolean flag = true;
		People p = dao.findById(id);
		if(p != null){
			p.setOpera("-1");
			flag = flag &&p.update();
		}
		return flag;
	}
}
